### PR TITLE
!! Secrets exposed !!

### PR DESCRIPTION
**Pull request by phiko-misc**
### **Please consider to not write secrets in blank text instead use env file for secret**

I have removed all yours firebase secrets from the `firebase.ts` file and maded them nextjs compatible also to the frontend.

Have a nice day. See your on SDE

### CODE REVIEW

**Comment by kasp416h** [comment]
Hej

**Comment by ItzNimaB** [comment]
Thank you for your request.

Although the secrets are exposed, the authorization is handled on the firebase control panel.
We control which domains are allowed to manipulate data via our API keys.
Therefore, the API keys are not required to be hidden 😃

**Comment by phiko-misc** [comment]
Okay so be sure to not allow localhost ;)

**Comment by phiko-misc** [comment]
> Thank you for your request.
> 
> Although the secrets are exposed, the authorization is handled on the firebase control panel. We control which domains are allowed to manipulate data via our API keys. Therefore, the API keys are not required to be hidden 😃

Okay so be sure to not allow localhost ;)

**Pull request closed without merging**
